var sentances = [
	"As you know from our new business success last year, Worldgroup's ability to manage all aspects of our clients' businesses has given us a competitive edge in growing with both existing and new clients",
	"To continue with this success, we must stay focused on embracing every new client opportunity that arises while also constantly improving the quality of the fundamentals of our business",
	"As part of this continuing drive to cross-sell our global resources and out-deliver the competition, I'm pleased to announce that Alex Lubar has been promoted to the new position of Global CMO for McCann Worldgroup",
	"Those of you who have had the opportunity to work with Alex know the qualities that make him so effective in business development",
	"In addition to his tenacity, he relishes the complexity of brand challenges",
	"He also knows how to work with leadership to harness our global resources and find new ways to deliver our multiplatform capabilities",
	"Since joining us, Alex has helped drive our regional and global new business success by effectively leveraging the full resources of Worldgroup in North America",
	"This has contributed to McCann adding business last year from clients such as the United States Postal Service, Lockheed Martin, Zurich Insurance, SABIC, Jose Cuervo, the American Frozen Food Institute and Ignite Restaurant Group",
	"Please join me in congratulating Alex on his new role",
	"Today, as we begin the New Year, I am pleased to announce that Rob Reilly is joining us from Crispin Porter + Bogusky as Global Creative Chairman of McCann Worldgroup",
	"In addition, Linus Karlsson has been promoted to Creative Chairman of Commonwealth, and Andreas Dahlqvist has been promoted to Chief Creative Officer of Commonwealth and also named President of the McCann Creative Leadership Council",
	"Rob is an incredible talent",
	"He understands how to navigate today's attention-challenged, media-fragmented consumer world using creativity that has the sharpest strategic intent across any and all platforms, cultures, and geographies",
	"He will be responsible for driving all our resources and disciplines together in a creatively synchronized way to solve brand challenges for our clients as well as having creative oversight for the McCann brand globally",
	"Rob joined CP+B in 2002, after spending a decade at a number of New York ad agencies, including McCann",
	"He began his CP+B career as a copywriter, creating some of the most talked about campaigns in history",
	"In his role as Worldwide Chief Creative Officer, he drove the creative vision for all of CP+B's clients around the globe",
	"A highly-awarded creative, Rob's work has been recognized at Cannes with multiple Titanium and Grand Prix Lions as well as three Interactive Agency of the Year awards",
	"He has served on a number of industry awards juries, including as President of the Cannes Titanium and Integrated Jury",
	"Rob is also a member of the Cannes Chimera and the Facebook Creative Council, a group that advises on advertising product ideas and agency concerns",
	"Linus, in addition to his responsibilities for Commonwealth and Chevy, will be starting a new venture in the spring",
	"We are very excited about this",
	"At heart, Linus is a change-maker and starting something innovative and new is a terrific use of his talent",
	"Andreas will be taking on a dual role as Chief Creative Officer of Commonwealth and as President of the McCann Creative Leadership Council",
	"We are in the process of working with Andreas and Rob to redefine how the CLC will work to lead and inspire our creative excellence throughout the network",
	"More to come in the near future on this",
	"With the addition of Rob and the new roles of Linus and Andreas teamed with Luca Lindner and our enviable Worldgroup creative leadership including—Prasoon Joshi, Washington Olivetto, Joyce King Thomas, Monica Moro, Leandro Raposo and John Mescall as well as the rest of our creative teams around the world from NY to London, North and South America to Europe, the Middle East, Africa and Asia Pacific—we have in place arguably the best creative leadership team in the business",
	"Please join me in welcoming Rob and congratulating Linus and Andreas on their new roles",
	"Finally, I want to thank all of you for what we've accomplished in 2013",
	"It was a great year for us",
	"Our success was solid across all areas of our business, disciplines and agencies—in our relationships with our clients, in the quality and effectiveness of our work, and in the awards and industry recognition we received",
	"I look forward to this exciting momentum continuing in 2014",
	"It gives me great pleasure to announce Luca Lindner's promotion to the position of President, McCann Worldgroup",
	"Luca is a true globalist and a key architect behind the success of McCann, establishing himself not only as one of the industry's most experienced multiplatform and global marketing leaders, but also as one of the most respected and admired members of our team",
	"He was named President of the Americas, Middle East and Africa for McCann Worldgroup in late 2012 and is one of the world's most respected global leaders, having directly overseen multinational clients and McCann operations in Latin America, North America, Europe, Africa, and the Middle East",
	"Additionally, he has played a leading role in overseeing McCann's global client capabilities and developed innovative dedicated resources such as the global McCann XBC team for MasterCard",
	"He first joined McCann in August 2004 as CEO of McCann Mexico and Deputy Regional Director of Latin America/Caribbean, and then rose to become Regional Director the next year",
	"Prior to joining McCann, he served as Vice Chairman of Leo Burnett EMEA and President of Burnett's Fiat Coordination Center",
	"Luca previously spent four years as CEO of the Conquest & Red Cell Network in Europe",
	"He began his agency career at TBWA in Paris, and then served as Managing Director of TBWA Rome and Client Service Director of TBWA Italy",
	"Luca will temporarily take up residence in Europe and will be responsible for driving McCann's businesses throughout the world to deliver integrated marketing solutions across our agencies to serve our clients",
	"Please join me in congratulating Luca on his new role",
	"As we enter the last few months of the year, I'm pleased to report that we are making terrific progress",
	"Over the last few weeks, I've traveled to Asia and the Middle East, meeting with clients and our key leadership",
	"The creative output and marketing ideas that I am seeing around the world and across all of our disciplines are fantastic",
	"And it is gratifying to hear from clients that our work and your efforts are making a difference and contributing to their success",
	"The impact of your smart thinking and creativity is being reflected in our continued growth and business success, including the addition of several new assignments from our global clients as well as wins of new regional and local clients",
	"And, as you have seen in my notes about creative awards, our outstanding work rightly is being saluted by the industry",
	"But as I have noted before, the environment in which we operate remains competitive",
	"That won't change",
	"To succeed, we must stay focused on improving the quality of all the fundamentals of our business, embracing every new opportunity that arises with both existing and new clients, and delivering on the Worldgroup ability to manage all aspects of our clients' businesses in ways that our competitors can't",
	"It has been a great year so far",
	"And, thanks to you, we have the momentum to take us through the remainder of the year and into the next",
	"As we enter the back half of the year, I want to update you on our performance",
	"As you know from recent announcements about awards and new business, our positive momentum is continuing",
	"Thanks to your commitment and great work, we have been making real progress in many important areas—in new business, in our client relationships, and in our creative reputation",
	"Importantly, we are seeing new assignments and greater creative work across the system",
	"All of our regions and disciplines are making progress",
	"Latin America's strong performance was bolstered with new Coca-Cola regional work, and Asia Pacific's growth was supported by several major new telecom and financial services clients",
	"North America continues to win significant new business across a broad spectrum of clients",
	"And, while consumer spending has not yet rebounded across Europe, the region added some important local assignments and spearheaded our multinational Zurich and Carlsberg wins",
	"Momentum, MRM and McCann Health continue to make strides in their respective sectors and have all been recently recognized as best-in-class agencies in their respective disciplines",
	"With McCann Melbourne's record-breaking performance for “Dumb Ways to Die” at Cannes still fresh in our minds, please join me in once again congratulating the team on their performance and to again congratulate all the creatively-recognized offices and teams who contributed to our incredible success at the award shows this year",
	"Overall, our recent new business and creative momentum has strengthened our reputation, enhanced our ability to demonstrate the vitality of our multiplatform approach and expanded our opportunities to cross-sell our multifaceted competencies to current and potential clients",
	"For those of you who are on or are planning to go on holiday over the summer, I hope you enjoy",
	"Keep up the good work and look forward to a great remainder of the year",
	"Last night, in front of a cheering crowd of approximately 1,100 of our industry peers, we were awarded top honors for our creative work at the D&AD Awards 2013 in London, widely considered one of the most prestigious awards for advertising and art direction",
	"We won more awards than ever and our Melbourne office was awarded a world-record-breaking five Yellow Pencils (recognizing the industry's most outstanding work) and a Black Pencil (the show's rarest and most coveted honor) for its “Dumb Ways To Die” campaign, an amazing performance that resulted in Melbourne being named D&AD's “Agency Of The Year",
	"London also won a Yellow Pencil for the “Games Maker” campaign for the London Olympics and The Martin Agency won a Yellow Pencil for the “Clouds Over Cuba” campaign for The JFK Presidential Library & Museum",
	"As you know from my previous notes, 2013 is shaping up as a fantastic year for our clients' businesses and for our creative reputation",
	"We have made impressive showings at all of the global, regional and local awards shows this year",
	"We have also won a significant amount of new business and have been awarded organic businessopportunities from our existing clients",
	"I want everyone to know how proud I am of the work you are doing",
	"Please join me in congratulating our folks in Australia and London and our friends at The Martin Agency for their award-winning work",
	"I am very pleased to announce that Suzanne Powers will join us as our new Global Chief Strategy Officer",
	"We have selected Suzanne after an extensive search to find a candidate who has the energy, passion and skills to lead our incredibly talented group of strategic executives",
	"She brings us a unique perspective on how to build global insights and ideas across our brands, geographies and culture",
	"One of our biggest competitive advantages is our strategic leadership and our ability to provide clients with multiplatform creative and strategic ideas that help differentiate them in a highly competitive environment",
	"Many of our long-term clients, such as General Motors, General Mills, MasterCard, Coca-Cola, Nestlé, and L'Oréal, have remained our partners for this exact reason",
	"Our success as an agency can be directly attributed to the terrific strategic team that we have in place and the incredible insights that that the McCann Truth Central team provides",
	"Suzanne joins us from Crispin Porter + Bogusky, where she served as Global Strategy Officer and was charged with leading the global development of the agency, working across all CP+B offices and brands",
	"Prior to CP+B, she was the global strategy director of TBWA, where she led brands including Mars, Nivea, and GSK",
	"She will report will report to Luca and Gustavo and will work closely with them as we continue to create strategic opportunities for all of our clients and prospects",
	"Please join me in welcoming Suzanne",
	"This morning, Advertising Age published 'Creativity 50', its annual list of the 50 most influential creative thinkers and doers, and our very own Linus Karlsson and John Mescall were included among an incredible list of honorees",
	"They are amongst a select group that represents a broad spectrum of disciplines, everyone from executors of outer-space stunts to digital entrepreneurs and zombie-makers",
	"It's a range of innovators that includes the likes of Jay Z to the band Daft Punk to Greg Nicotero, Special Effects Make-Up Guru and Executive Producer of 'The Walking Dead'",
	"Less than 10 agency creatives are recognized and the fact that both Linus and John are included is a testament to the incredible work they have been doing for us",
	"Please join me in congratulating Linus and John on this incredible honor",
	"I am delighted to announce Bill Kolb's promotion to the newly created position of Chairman and CEO of Commonwealth, our worldwide dedicated Chevrolet agency",
	"Bill, who has been CEO of MRM for the last two years, will also continue to support MRM in the role of Chairman",
	"Bill is one of our most experienced multiplatform and global marketing executives",
	"He first joined McCann Worldgroup 12 years ago as head of an expanded international Retail Marketing Group and then became COO of Momentum",
	"He later moved to the dedicated MRM COO position in 2006",
	"As previously announced, heading MRM will be co-presidents Michael Mclaren andHank Summy, both of whom took on new global MRM roles in April",
	"Bill's record at MRM has been impressive, in both driving the agency's overall growth and reputation",
	"Bill brings to our global GM business the kind of collaborative, energetic and insightful leadership that will help us continue to partner with this important client",
	"Bill will work closely and collaboratively with the Commonwealth leadership team of Linus Karlsson, Joe Garcia,Kate MacNevin and Matt Woehrmann",
	"He will also have oversight of all of our Detroit operations",
	"Please join me in congratulating Bill on his new role"
]
